[package]
name = "gameoff"
version = "0.1.0"
authors = []

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", rev = "master" }
game-core = { path = "../game-core" }
env_logger = "0.6.0"

# [profile.release]
# lto = true
