[package]
name = "game-core"
version = "0.1.0"
authors = ["Jane Lusby <jlusby42@gmail.com>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", rev = "master" }
tiled = "0.8.0"
