[package]
name = "game-core"
version = "0.1.0"
authors = ["Jane Lusby <jlusby42@gmail.com>"]

[dependencies]
amethyst = "0.9.0"
cgmath="0.16.1"
amethyst-rhusics = { git = "https://github.com/amethyst/amethyst-rhusics" }
tiled = "0.8.0"
rand = "0.6.0"
